version: "3.8"

services:
  backend:
    image: chillys-radio
    build:
      context: ./chillys-radio
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${SPRING_DATASOURCE_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"

  frontend:
    image: chillys-radio-fe
    build:
      context: ./chillys-radio-fe
    ports:
      - "80:80"
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
    depends_on:
      - backend

  db:
    image: postgres:16.0
#    container_name: postgres
#    restart: always
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_DB_NAME}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#    networks:
#      - app-network

volumes:
  db-data:

#networks:
#  app-network:

