spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        auto_quote_keyword: true
  key_access: ${KEY_ACCESS}
  key_refresh: ${KEY_REFRESH}
  mail:
    password: rmvv nrke oyjs zvam
    username: chillysradio@gmail.com
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

server:
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    display-request-duration: true
    try-it-out-enabled: true
  default-produces-media-type: application/json
logging:
  level:
    org:
      springframework:
        security: DEBUG
        mail: DEBUG