name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.chillys_deploy }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -i private_key target/*.jar deploy@57.129.44.101:/home/deploy/backend/app.jar
          ssh -i private_key deploy@57.129.44.101 "sudo systemctl restart backend"
